---

# tasks file for ec2 instances
- name: Create EC2 Instance
  ec2:
    id: "{{ item }}"
    instance_tags:
      Name: "{{ item }}"
    instance_type: "{{ instance_type }}"
    key_name: "{{ key_name }}"
    group: "{{ sec_group_name }}"
    image: "{{ image_id }}"
    region: "{{ region }}"
    vpc_subnet_id: "{{ vpc_subnetid_facts['subnets'][0]['id'] }}"
    assign_public_ip: yes
  with_items:
    "{{ ec2_hosts }}"
